import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {ambassadorGuideGroups} from './src/data/ambassadorContent';
import {installerGuideGroups, installerSteps} from './src/data/installerContent';

const topicDocId = (groupId: string, topicId: string) =>
  `dai-su-xanh/${groupId}/${topicId}/index`;

const daiSuXanhSidebar = ambassadorGuideGroups.map((group) => ({
  type: 'category' as const,
  label: group.title,
  className: 'ambassador-sidebar-group',
  collapsible: true,
  collapsed: false,
  link: {
    type: 'generated-index' as const,
    title: group.title,
    slug: `/dai-su-xanh/${group.id}`,
  },
  items: group.topics.map((topic) => {
    const id = topicDocId(topic.groupId, topic.id);

    if (topic.articles.length === 0) {
      return {type: 'doc' as const, id, label: topic.title};
    }

    return {
      type: 'category' as const,
      label: topic.title,
      collapsible: true,
      collapsed: true,
      link: {type: 'doc' as const, id},
      items: topic.articles.map((article) => ({
        type: 'doc' as const,
        id: `dai-su-xanh/${topic.groupId}/${topic.id}/${article.id}`,
        label: article.title,
      })),
    };
  }),
}));

const sidebars: SidebarsConfig = {
  daiSuXanhSidebar,
  nhaLapDatSidebar: installerGuideGroups.map(group => ({
    type: 'category' as const,
    label: group.title,
    className: 'ambassador-sidebar-group',
    collapsed: false,
    link: {type: 'generated-index' as const, title: group.title, slug: `/nha-lap-dat/${group.id}`},
    items: [
      ...group.articles.map(article => ({type: 'doc' as const, id: `nha-lap-dat/${group.id}/${article.id}`})),
      ...(group.id === 'su-dung-nen-tang' ? [{
        type: 'category' as const,
        label: 'Hướng dẫn thao tác 6 bước',
        collapsed: true,
        link: {type: 'doc' as const, id: 'nha-lap-dat/su-dung-nen-tang/sau-buoc/index'},
        items: installerSteps.map(step => `nha-lap-dat/su-dung-nen-tang/sau-buoc/${step.id}`),
      }] : []),
    ],
  })),
  khachHangSidebar: [{type: 'autogenerated', dirName: 'khach-hang'}],
  hoTroSidebar: [{type: 'autogenerated', dirName: 'ho-tro'}],
};

export default sidebars;

